### ISSUE TITLE
[issue22] test__login_parameters unit test fails on Linux.

### ISSUE THREAD

**Issue by sumanthvepa** [sumanthvepa/zaphod#22]
Unit test output:
======================================================================
ERROR: test__login_parameters_bridged (m42.test.test_zvm.TestVirtualMachine)
Test the login parameters of a VM with bridged interface are
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/workspaces/svepa/zaphod/m42/test/test_zvm.py", line 131, in test__login_parameters_bridged
    = vm._login_parameters()
  File "/workspaces/svepa/zaphod/m42/zvm.py", line 83, in _login_parameters
    + 'and that your host adapter supports bridging.')
VirtualMachineError: Could not get IP address for VM with MAC address 0800276EA107. Check that the VM is running and that the user id you are running zaphod as, has permission to access the raw host adapter interface and that your host adapter supports bridging.

----------------------------------------------------------------------

**Comment by sumanthvepa** [comment]
No longer an issue in release v0.4prealpha2
