### ISSUE TITLE
bug-unittest-failure-test-load: Fix inablity to finde default.zbox. 

### ISSUE THREAD

**Issue by sumanthvepa** [sumanthvepa/zaphod#51]
Unittest error log:
======================================================================
ERROR: test_load (m42.test.test_zbox.TestZBox)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/workspaces/svepa/zaphod/m42/test/test_zbox.py", line 32, in test_load
    box = zbox.load('default.zbox')
  File "/workspaces/svepa/zaphod/m42/zbox.py", line 40, in load
    return ZBox(yaml_config.load(zbox_filename))
  File "/workspaces/svepa/zaphod/m42/yaml_config.py", line 38, in load
    with open(filename, 'r') as ifs:
IOError: [Errno 2] No such file or directory: 'default.zbox'

**Comment by sumanthvepa** [comment]
Fixed with commit f96b92d7cdb666a25544f8d02121a3ad6f3e8ca3
