### ISSUE TITLE
bug-unittest-failure-test-copy-file: Unable to find file to copy. 

### ISSUE THREAD

**Issue by sumanthvepa** [sumanthvepa/zaphod#52]
======================================================================
ERROR: test_copy_file (m42.test.test_zvm.TestVirtualMachine)
Check that a file can be copied correctly from the host to a VM.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/workspaces/svepa/zaphod/m42/test/test_zvm.py", line 282, in test_copy_file
    vm_path='/root/test.txt')
  File "/workspaces/svepa/zaphod/m42/zvm.py", line 244, in copy_file
    sftp.put(host_path, vm_path)
  File "/usr/lib/python2.7/site-packages/paramiko/sftp_client.py", line 667, in put
    file_size = os.stat(localpath).st_size
OSError: [Errno 2] No such file or directory: 'test.txt'

**Comment by sumanthvepa** [comment]
Fixed with commit f96b92d7cdb666a25544f8d02121a3ad6f3e8ca3
